{{- $root := .Values.root }}
{{- range .Values.projects }}
  {{- $project := . }}
  {{- range .clusters }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $project.name }}-{{ .name }}
  namespace: {{ $root.namespace }}
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .server }}
  source:
    repoURL: {{ $root.repoURL }}
    targetRevision: {{ $root.targetRevision }}
    path: rendered-manifests/{{ $project.name }}/{{ .name }}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
{{- end }}
{{- end }}
