---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
# yamllint disable-file
# This file is not valid YAML because it is a template
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collab-board-devtest-east
  namespace: platform-gitops
spec:
  destination:
    name: devtest-east
    namespace: collab-board
  source:
    repoURL: https://github.com/example/collab-board-manifests
    targetRevision: main
    path: .
  project: collab-board
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collab-board-devtest-west
  namespace: platform-gitops
spec:
  destination:
    name: devtest-west
    namespace: collab-board
  source:
    repoURL: https://github.com/example/collab-board-manifests
    targetRevision: main
    path: .
  project: collab-board
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collab-board-prod-east
  namespace: platform-gitops
spec:
  destination:
    name: prod-east
    namespace: collab-board
  source:
    repoURL: https://github.com/example/collab-board-manifests
    targetRevision: main
    path: .
  project: collab-board
  syncPolicy:
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collab-board-prod-west
  namespace: platform-gitops
spec:
  destination:
    name: prod-west
    namespace: collab-board
  source:
    repoURL: https://github.com/example/collab-board-manifests
    targetRevision: main
    path: .
  project: collab-board
  syncPolicy:
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging-devtest-east
  namespace: platform-gitops
spec:
  destination:
    name: devtest-east
    namespace: messaging
  source:
    repoURL: https://github.com/example/messaging-manifests
    targetRevision: main
    path: .
  project: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging-devtest-west
  namespace: platform-gitops
spec:
  destination:
    name: devtest-west
    namespace: messaging
  source:
    repoURL: https://github.com/example/messaging-manifests
    targetRevision: main
    path: .
  project: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging-prod-east
  namespace: platform-gitops
spec:
  destination:
    name: prod-east
    namespace: messaging
  source:
    repoURL: https://github.com/example/messaging-manifests
    targetRevision: main
    path: .
  project: messaging
  syncPolicy:
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging-prod-west
  namespace: platform-gitops
spec:
  destination:
    name: prod-west
    namespace: messaging
  source:
    repoURL: https://github.com/example/messaging-manifests
    targetRevision: main
    path: .
  project: messaging
  syncPolicy:
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: case-management-devtest-east
  namespace: platform-gitops
spec:
  destination:
    name: devtest-east
    namespace: case-management
  source:
    repoURL: https://github.com/example/case-management-manifests
    targetRevision: main
    path: .
  project: case-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: case-management-devtest-west
  namespace: platform-gitops
spec:
  destination:
    name: devtest-west
    namespace: case-management
  source:
    repoURL: https://github.com/example/case-management-manifests
    targetRevision: main
    path: .
  project: case-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: case-management-prod-east
  namespace: platform-gitops
spec:
  destination:
    name: prod-east
    namespace: case-management
  source:
    repoURL: https://github.com/example/case-management-manifests
    targetRevision: main
    path: .
  project: case-management
  syncPolicy:
---
# Source: argo-cd-app-of-apps-chart/templates/cluster-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: case-management-prod-west
  namespace: platform-gitops
spec:
  destination:
    name: prod-west
    namespace: case-management
  source:
    repoURL: https://github.com/example/case-management-manifests
    targetRevision: main
    path: .
  project: case-management
  syncPolicy:
