---
name: Lint and Validate Helm Chart

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Install yq and yamllint
        env:
          YAMLLINT_VERSION: 1.37.1
          YQ_VERSION: v4.45.4
        run: |
          pip install yamllint==${YAMLLINT_VERSION}
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 \
            -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Validate with yq
        run: |
          find . -name '*.yaml' -o -name '*.yml' -exec yq eval {} +

      - name: Lint with yamllint
        run: |
          find . -name '*.yaml' -o -name '*.yml' -exec yamllint {} +

      - name: Lint Helm chart
        run: helm lint ./chart
