name: Lint and Validate Helm Chart

on:
  pull_request:
    types: [synchronize, opened, reopened] 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Install yq and yamllint
        env:
          YAMLLINT_VERSION: 1.37.1
          YQ_VERSION: v3.4.3
        run: pip install yamllint==${YAMLLINT_VERSION} yq==${YQ_VERSION}

      - name: Validate Chart.yaml
        run: |
          yq eval '.' ./chart/Chart.yaml

      - name: Check for valid YAML in templates
        run: |
          find ./chart/templates -name '*.yaml' -exec yamllint {} +

      - name: Lint Helm chart
        run: helm lint ./chart
