---
name: Render Argo CD Manifests

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'rendered-manifests/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Render Helm templates
        run: |
          helm dependency update ./chart
          helm template argo-cd-app-of-apps ./chart \
            --output-dir rendered-manifests

      - name: Create Pull Request for rendered manifests
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update rendered Argo CD manifests"
          branch: update/rendered-manifests-${{ github.sha }}
          title: "Update rendered Argo CD manifests - ${{ github.sha }}"
          body: >
            This PR updates the rendered Argo CD manifests
            based on the latest changes.
          add-paths: rendered-manifests

      - name: Upload rendered manifests as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests
          path: rendered-manifests
