name: Render Argo CD Manifests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Render Helm templates
        run: |
          helm dependency update ./argo-cd-app-of-apps-chart
          helm template argo-cd-app-of-apps ./argo-cd-app-of-apps-chart \
            --output-dir argo-cd-rendered-manifests

      - name: Upload rendered manifests as artifact
        uses: actions/upload-artifact@v4
        with:
          name: argo-cd-rendered-manifests
          path: argo-cd-rendered-manifests