---
archiver:
    name: archiver
  repoURL: https://github.com/DaneWeber/gitops-masterclass-applications
  clusters:
    - name: devtest-east
      namespace: argocd
      targetRevision: main
      path: example
    - name: prod-east
      namespace: argocd
      targetRevision: main
      path: example
